#!/usr/bin/env node

/**
 * 🚀 Pulse CRM - Advanced Deployment Utility
 * Node.js companion script for Vercel deployment automation
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m'
};

class DeploymentUtility {
  constructor() {
    this.projectRoot = process.cwd();
    this.packageJson = this.loadPackageJson();
    this.startTime = Date.now();
  }

  // Utility methods
  log(message, color = 'reset') {
    console.log(`${colors[color]}${message}${colors.reset}`);
  }

  success(message) {
    this.log(`✅ ${message}`, 'green');
  }

  warning(message) {
    this.log(`⚠️  ${message}`, 'yellow');
  }

  error(message) {
    this.log(`❌ ${message}`, 'red');
  }

  info(message) {
    this.log(`ℹ️  ${message}`, 'blue');
  }

  loadPackageJson() {
    try {
      const packagePath = path.join(this.projectRoot, 'package.json');
      return JSON.parse(fs.readFileSync(packagePath, 'utf8'));
    } catch (error) {
      this.error('Could not load package.json');
      process.exit(1);
    }
  }

  // Generate secure random secret
  generateSecureSecret(length = 32) {
    return crypto.randomBytes(length).toString('base64');
  }

  // Check if file exists
  fileExists(filePath) {
    return fs.existsSync(path.join(this.projectRoot, filePath));
  }

  // Read file content
  readFile(filePath) {
    try {
      return fs.readFileSync(path.join(this.projectRoot, filePath), 'utf8');
    } catch (error) {
      return null;
    }
  }

  // Write file content
  writeFile(filePath, content) {
    try {
      fs.writeFileSync(path.join(this.projectRoot, filePath), content, 'utf8');
      return true;
    } catch (error) {
      this.error(`Failed to write ${filePath}: ${error.message}`);
      return false;
    }
  }

  // Execute command
  executeCommand(command, options = {}) {
    try {
      const result = execSync(command, { 
        encoding: 'utf8', 
        cwd: this.projectRoot,
        ...options 
      });
      return { success: true, output: result };
    } catch (error) {
      return { success: false, error: error.message, output: error.stdout };
    }
  }

  // Validate Node.js and NPM versions
  validateEnvironment() {
    this.log('\n📋 Validating Environment', 'blue');
    this.log('========================', 'blue');

    // Check Node.js version
    const nodeVersion = process.version;
    const nodeMajor = parseInt(nodeVersion.slice(1).split('.')[0]);
    
    if (nodeMajor >= 18) {
      this.success(`Node.js version: ${nodeVersion}`);
    } else {
      this.error(`Node.js version ${nodeVersion} is too old. Please upgrade to 18+`);
      return false;
    }

    // Check NPM version
    const npmResult = this.executeCommand('npm --version');
    if (npmResult.success) {
      this.success(`NPM version: ${npmResult.output.trim()}`);
    } else {
      this.error('NPM not found');
      return false;
    }

    // Check if in correct directory
    if (!this.fileExists('package.json')) {
      this.error('package.json not found. Run this script from project root.');
      return false;
    }

    this.success('Environment validation complete');
    return true;
  }

  // Generate environment variables
  generateEnvironmentVariables() {
    this.log('\n🔐 Generating Environment Variables', 'blue');
    this.log('==================================', 'blue');

    const nextAuthSecret = this.generateSecureSecret();
    const timestamp = new Date().toISOString();

    const envContent = `# Generated by Pulse CRM Deployment Utility
# Generated on: ${timestamp}

# Core Application
NODE_ENV=production
NEXTAUTH_SECRET=${nextAuthSecret}

# Database Configuration
# ⚠️  Update these with your actual Neon PostgreSQL credentials
POSTGRES_URL=postgresql://username:password@host/database
POSTGRES_PRISMA_URL=postgresql://username:password@host/database?pgbouncer=true&connect_timeout=15
POSTGRES_URL_NON_POOLING=postgresql://username:password@host/database

# Application URLs
# ⚠️  Update with your actual Vercel deployment URL
NEXTAUTH_URL=https://your-app-name.vercel.app
APP_URL=https://your-app-name.vercel.app

# Email Configuration (Required for e-signatures)
# ⚠️  Update with your actual SMTP credentials
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-gmail-app-password
SMTP_FROM="PulseCRM <noreply@your-domain.com>"

# Document Signing Recipients
DEFAULT_EMAIL=admin@your-domain.com
RECIPIENT_EMAILS=email1@your-domain.com,email2@your-domain.com

# Optional: Analytics
VERCEL_ANALYTICS_ID=
`;

    if (this.writeFile('.env.production', envContent)) {
      this.success('Production environment file created');
      this.info(`Generated NEXTAUTH_SECRET: ${nextAuthSecret}`);
      return nextAuthSecret;
    }
    return null;
  }

  // Create deployment instructions
  createDeploymentInstructions(nextAuthSecret) {
    this.log('\n📝 Creating Deployment Instructions', 'blue');
    this.log('===================================', 'blue');

    const instructions = `# 🚀 Pulse CRM Deployment Instructions

## Environment Variables for Vercel Dashboard

Copy these environment variables to your Vercel project dashboard:

### Required Variables
\`\`\`
NODE_ENV=production
NEXTAUTH_SECRET=${nextAuthSecret}
NEXTAUTH_URL=https://your-app-name.vercel.app
\`\`\`

### Database (Update with your Neon PostgreSQL credentials)
\`\`\`
POSTGRES_URL=postgresql://username:password@host/database
POSTGRES_PRISMA_URL=postgresql://username:password@host/database?pgbouncer=true&connect_timeout=15
POSTGRES_URL_NON_POOLING=postgresql://username:password@host/database
\`\`\`

### Email (Update with your SMTP credentials)
\`\`\`
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-gmail-app-password
SMTP_FROM="PulseCRM <noreply@your-domain.com>"
\`\`\`

## Vercel Project Settings
- **Framework Preset:** Next.js
- **Build Command:** npm run build
- **Output Directory:** .next
- **Install Command:** npm install --legacy-peer-deps
- **Node.js Version:** 20.x

## Quick Deploy Links
- [Import to Vercel](https://vercel.com/new)
- [Neon Database](https://neon.tech)
- [Gmail App Passwords](https://support.google.com/accounts/answer/185833)

## Next Steps
1. Create Vercel project from GitHub repository
2. Add environment variables in Vercel dashboard
3. Configure custom domain (optional)
4. Deploy!

Generated on: ${new Date().toISOString()}
`;

    if (this.writeFile('DEPLOYMENT_INSTRUCTIONS.md', instructions)) {
      this.success('Deployment instructions created');
      return true;
    }
    return false;
  }

  // Test production build
  testProductionBuild() {
    this.log('\n🔨 Testing Production Build', 'blue');
    this.log('===========================', 'blue');

    // Set environment variables for build
    process.env.NODE_ENV = 'production';
    process.env.NEXTAUTH_URL = 'http://localhost:3000';
    
    // Clean previous build
    if (this.fileExists('.next')) {
      this.info('Cleaning previous build...');
      const cleanResult = this.executeCommand('rm -rf .next');
      if (cleanResult.success) {
        this.success('Previous build cleaned');
      }
    }

    // Run build
    this.info('Running production build...');
    const buildResult = this.executeCommand('npm run build', { stdio: 'inherit' });
    
    if (buildResult.success) {
      this.success('Production build completed successfully');
      
      // Check build size
      if (this.fileExists('.next')) {
        const sizeResult = this.executeCommand('du -sh .next');
        if (sizeResult.success) {
          this.info(`Build size: ${sizeResult.output.trim().split('\t')[0]}`);
        }
      }
      return true;
    } else {
      this.error('Production build failed');
      return false;
    }
  }

  // Analyze dependencies
  analyzeDependencies() {
    this.log('\n📦 Analyzing Dependencies', 'blue');
    this.log('========================', 'blue');

    const deps = this.packageJson.dependencies || {};
    const devDeps = this.packageJson.devDependencies || {};
    
    this.info(`Production dependencies: ${Object.keys(deps).length}`);
    this.info(`Development dependencies: ${Object.keys(devDeps).length}`);

    // Check for problematic dependencies
    const problematicDeps = ['better-sqlite3', 'sqlite3', 'canvas'];
    const found = problematicDeps.filter(dep => deps[dep] || devDeps[dep]);
    
    if (found.length > 0) {
      this.warning(`Potentially problematic dependencies found: ${found.join(', ')}`);
      this.info('These should be in optionalDependencies for Vercel deployment');
    } else {
      this.success('No problematic dependencies found');
    }

    return true;
  }

  // Verify configuration files
  verifyConfiguration() {
    this.log('\n⚙️  Verifying Configuration', 'blue');
    this.log('===========================', 'blue');

    const configFiles = [
      { file: 'vercel.json', required: true },
      { file: 'next.config.js', required: true },
      { file: '.vercelignore', required: false },
      { file: 'tsconfig.json', required: true }
    ];

    let allGood = true;

    configFiles.forEach(({ file, required }) => {
      if (this.fileExists(file)) {
        this.success(`${file} found`);
      } else if (required) {
        this.error(`${file} missing (required)`);
        allGood = false;
      } else {
        this.warning(`${file} missing (optional)`);
      }
    });

    // Check vercel.json content
    if (this.fileExists('vercel.json')) {
      const vercelConfig = this.readFile('vercel.json');
      if (vercelConfig && vercelConfig.includes('nextjs')) {
        this.success('Vercel configuration appears correct');
      } else {
        this.warning('Vercel configuration may need review');
      }
    }

    return allGood;
  }

  // Check git status
  checkGitStatus() {
    this.log('\n📝 Checking Git Status', 'blue');
    this.log('=====================', 'blue');

    const statusResult = this.executeCommand('git status --porcelain');
    if (!statusResult.success) {
      this.warning('Not a git repository or git not available');
      return false;
    }

    const changes = statusResult.output.trim();
    if (changes) {
      this.warning('You have uncommitted changes:');
      console.log(changes);
      
      // Ask user if they want to commit
      const readline = require('readline');
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      return new Promise((resolve) => {
        rl.question('Do you want to commit these changes? (y/N): ', (answer) => {
          if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
            this.executeCommand('git add .');
            const commitResult = this.executeCommand('git commit -m "Prepare for Vercel deployment"');
            if (commitResult.success) {
              this.success('Changes committed');
            } else {
              this.error('Failed to commit changes');
            }
          }
          rl.close();
          resolve(true);
        });
      });
    } else {
      this.success('No uncommitted changes');
      return true;
    }
  }

  // Create deployment checklist
  createDeploymentChecklist() {
    const checklist = `# 📋 Pulse CRM Deployment Checklist

## Pre-Deployment ✅
- [x] Environment variables generated
- [x] Production build tested
- [x] Dependencies verified
- [x] Security checks completed
- [x] Git repository prepared

## Vercel Setup ⏳
- [ ] Import GitHub repository to Vercel
- [ ] Set Node.js version to 20.x
- [ ] Add environment variables from DEPLOYMENT_INSTRUCTIONS.md
- [ ] Configure custom domain (optional)

## Post-Deployment ⏳
- [ ] Test authentication flow
- [ ] Verify database connection
- [ ] Test email functionality
- [ ] Check document upload/download
- [ ] Verify e-signature workflow

## Database Setup ⏳
- [ ] Create Neon PostgreSQL database
- [ ] Update POSTGRES_URL environment variable
- [ ] Run initial database migration
- [ ] Test database connectivity

## Production Validation ⏳
- [ ] Site loads without errors
- [ ] User registration works
- [ ] Login/logout functionality
- [ ] Dashboard displays correctly
- [ ] All pages accessible
- [ ] Mobile responsiveness verified

Generated: ${new Date().toISOString()}
`;

    if (this.writeFile('DEPLOYMENT_CHECKLIST.md', checklist)) {
      this.success('Deployment checklist created');
      return true;
    }
    return false;
  }

  // Main deployment preparation flow
  async run() {
    this.log('🚀 Pulse CRM - Advanced Deployment Utility', 'cyan');
    this.log('==========================================', 'cyan');

    try {
      // Step 1: Validate environment
      if (!this.validateEnvironment()) {
        process.exit(1);
      }

      // Step 2: Analyze dependencies
      this.analyzeDependencies();

      // Step 3: Verify configuration
      if (!this.verifyConfiguration()) {
        this.warning('Configuration issues found. Deployment may fail.');
      }

      // Step 4: Generate environment variables
      const nextAuthSecret = this.generateEnvironmentVariables();
      if (!nextAuthSecret) {
        this.error('Failed to generate environment variables');
        process.exit(1);
      }

      // Step 5: Create deployment instructions
      this.createDeploymentInstructions(nextAuthSecret);

      // Step 6: Create deployment checklist
      this.createDeploymentChecklist();

      // Step 7: Test production build
      if (!this.testProductionBuild()) {
        this.error('Production build failed. Please fix errors before deploying.');
        process.exit(1);
      }

      // Step 8: Check git status
      await this.checkGitStatus();

      // Final summary
      this.log('\n🎉 Deployment Preparation Complete!', 'green');
      this.log('==================================', 'green');
      
      const duration = ((Date.now() - this.startTime) / 1000).toFixed(1);
      this.success(`Completed in ${duration} seconds`);
      
      this.log('\n📋 Next Steps:', 'yellow');
      this.log('1. Go to https://vercel.com/new', 'yellow');
      this.log('2. Import your GitHub repository', 'yellow');
      this.log('3. Configure environment variables using DEPLOYMENT_INSTRUCTIONS.md', 'yellow');
      this.log('4. Set Node.js version to 20.x', 'yellow');
      this.log('5. Deploy!', 'yellow');

      this.log('\n🔑 Generated NEXTAUTH_SECRET:', 'magenta');
      this.log(nextAuthSecret, 'bright');

    } catch (error) {
      this.error(`Deployment preparation failed: ${error.message}`);
      process.exit(1);
    }
  }
}

// Run the deployment utility
if (require.main === module) {
  const utility = new DeploymentUtility();
  utility.run().catch(error => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

module.exports = DeploymentUtility;