#!/bin/bash

# 🚀 Pulse CRM - Automated Vercel Deployment Script
# This script handles the complete deployment process automatically

set -e # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script configuration
PROJECT_NAME="pulse-crm"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$SCRIPT_DIR"

echo -e "${BLUE}🚀 Pulse CRM - Automated Deployment Script${NC}"
echo -e "${BLUE}================================================${NC}"
echo ""

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to generate secure secret
generate_secret() {
    if command_exists openssl; then
        openssl rand -base64 32
    else
        # Fallback method
        head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32 ; echo ''
    fi
}

# 1. Environment Setup and Validation
echo -e "${BLUE}📋 Step 1: Environment Setup and Validation${NC}"
echo "----------------------------------------"

# Check Node.js version
if command_exists node; then
    NODE_VERSION=$(node --version)
    print_status "Node.js version: $NODE_VERSION"
    
    # Verify Node.js >= 18
    NODE_MAJOR_VERSION=$(echo $NODE_VERSION | cut -d'.' -f1 | sed 's/v//')
    if [ "$NODE_MAJOR_VERSION" -lt 18 ]; then
        print_error "Node.js version must be >= 18. Please upgrade."
        exit 1
    fi
else
    print_error "Node.js not found. Please install Node.js >= 18."
    exit 1
fi

# Check npm
if command_exists npm; then
    NPM_VERSION=$(npm --version)
    print_status "NPM version: $NPM_VERSION"
else
    print_error "NPM not found. Please install NPM."
    exit 1
fi

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    print_error "package.json not found. Please run this script from the project root."
    exit 1
fi

print_status "Environment validation complete"
echo ""

# 2. Pre-deployment Cleanup and Optimization
echo -e "${BLUE}🧹 Step 2: Pre-deployment Cleanup${NC}"
echo "--------------------------------"

# Clean previous builds
if [ -d ".next" ]; then
    print_info "Cleaning previous build..."
    rm -rf .next
    print_status "Previous build cleaned"
fi

# Clean node_modules cache
if [ -d "node_modules/.cache" ]; then
    print_info "Cleaning node_modules cache..."
    rm -rf node_modules/.cache
    print_status "Cache cleaned"
fi

# Verify package.json engines
if grep -q '"engines"' package.json; then
    print_status "Node.js engines configured in package.json"
else
    print_warning "Consider adding Node.js engines to package.json for consistent deployments"
fi

echo ""

# 3. Environment Variables Generation
echo -e "${BLUE}🔐 Step 3: Environment Variables Setup${NC}"
echo "-----------------------------------"

# Generate production environment file
ENV_PRODUCTION_FILE=".env.production"
ENV_EXAMPLE_FILE=".env.example"

print_info "Generating production environment variables..."

# Generate secure NEXTAUTH_SECRET
NEXTAUTH_SECRET=$(generate_secret)

# Create production environment file
cat > "$ENV_PRODUCTION_FILE" << EOF
# Generated by Pulse CRM Deployment Script
# Generated on: $(date)

# Core Application
NODE_ENV=production
NEXTAUTH_SECRET=$NEXTAUTH_SECRET

# Database Configuration
# ⚠️  Update these with your actual Neon PostgreSQL credentials
POSTGRES_URL=postgresql://username:password@host/database
POSTGRES_PRISMA_URL=postgresql://username:password@host/database?pgbouncer=true&connect_timeout=15
POSTGRES_URL_NON_POOLING=postgresql://username:password@host/database

# Application URLs
# ⚠️  Update with your actual Vercel deployment URL
NEXTAUTH_URL=https://your-app-name.vercel.app
APP_URL=https://your-app-name.vercel.app

# Email Configuration (Required for e-signatures)
# ⚠️  Update with your actual SMTP credentials
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-gmail-app-password
SMTP_FROM="PulseCRM <noreply@your-domain.com>"

# Document Signing Recipients
DEFAULT_EMAIL=admin@your-domain.com
RECIPIENT_EMAILS=email1@your-domain.com,email2@your-domain.com

# Optional: Analytics
VERCEL_ANALYTICS_ID=
EOF

print_status "Production environment file created: $ENV_PRODUCTION_FILE"

# Create deployment instructions
cat > "DEPLOYMENT_INSTRUCTIONS.md" << EOF
# 🚀 Pulse CRM Deployment Instructions

## Environment Variables for Vercel Dashboard

Copy these environment variables to your Vercel project dashboard:

### Required Variables
\`\`\`
NODE_ENV=production
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
NEXTAUTH_URL=https://your-app-name.vercel.app
\`\`\`

### Database (Update with your Neon PostgreSQL credentials)
\`\`\`
POSTGRES_URL=postgresql://username:password@host/database
POSTGRES_PRISMA_URL=postgresql://username:password@host/database?pgbouncer=true&connect_timeout=15
POSTGRES_URL_NON_POOLING=postgresql://username:password@host/database
\`\`\`

### Email (Update with your SMTP credentials)
\`\`\`
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-gmail-app-password
SMTP_FROM="PulseCRM <noreply@your-domain.com>"
\`\`\`

## Vercel Project Settings
- **Framework Preset:** Next.js
- **Build Command:** npm run build
- **Output Directory:** .next
- **Install Command:** npm install --legacy-peer-deps
- **Node.js Version:** 20.x

## Next Steps
1. Create Vercel project from GitHub repository
2. Add environment variables in Vercel dashboard
3. Configure custom domain (optional)
4. Deploy!

Generated on: $(date)
EOF

print_status "Deployment instructions created: DEPLOYMENT_INSTRUCTIONS.md"
echo ""

# 4. Dependencies Installation and Verification
echo -e "${BLUE}📦 Step 4: Dependencies Installation${NC}"
echo "--------------------------------"

print_info "Installing dependencies with legacy peer deps..."
npm install --legacy-peer-deps --no-audit

if [ $? -eq 0 ]; then
    print_status "Dependencies installed successfully"
else
    print_error "Dependencies installation failed"
    exit 1
fi

# Check for security vulnerabilities
print_info "Checking for security vulnerabilities..."
npm audit --audit-level moderate || true

echo ""

# 5. Build Verification
echo -e "${BLUE}🔨 Step 5: Local Build Test${NC}"
echo "-------------------------"

print_info "Running production build test..."

# Set temporary environment variables for build
export NODE_ENV=production
export NEXTAUTH_SECRET="$NEXTAUTH_SECRET"
export NEXTAUTH_URL="http://localhost:3000"

# Run build
npm run build

if [ $? -eq 0 ]; then
    print_status "Production build completed successfully"
else
    print_error "Production build failed"
    exit 1
fi

# Check build output
if [ -d ".next" ]; then
    BUILD_SIZE=$(du -sh .next | cut -f1)
    print_status "Build output size: $BUILD_SIZE"
else
    print_error "Build output directory not found"
    exit 1
fi

echo ""

# 6. Git Repository Verification
echo -e "${BLUE}📝 Step 6: Git Repository Verification${NC}"
echo "-----------------------------------"

# Check if git repository exists
if [ -d ".git" ]; then
    print_status "Git repository found"
    
    # Check for uncommitted changes
    if ! git diff-index --quiet HEAD --; then
        print_warning "You have uncommitted changes. Consider committing them before deployment."
        
        # Show status
        echo ""
        print_info "Git status:"
        git status --porcelain
        echo ""
        
        read -p "Do you want to commit these changes? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            print_info "Staging all changes..."
            git add .
            
            read -p "Enter commit message (or press Enter for default): " COMMIT_MESSAGE
            if [ -z "$COMMIT_MESSAGE" ]; then
                COMMIT_MESSAGE="Prepare for Vercel deployment - $(date)"
            fi
            
            git commit -m "$COMMIT_MESSAGE"
            print_status "Changes committed"
        fi
    else
        print_status "No uncommitted changes"
    fi
    
    # Get current branch
    CURRENT_BRANCH=$(git branch --show-current)
    print_info "Current branch: $CURRENT_BRANCH"
    
    # Check if remote exists
    if git remote get-url origin >/dev/null 2>&1; then
        REMOTE_URL=$(git remote get-url origin)
        print_status "Remote repository: $REMOTE_URL"
    else
        print_warning "No remote repository configured"
    fi
else
    print_warning "Not a git repository. Initialize git for automatic deployments."
fi

echo ""

# 7. Vercel Configuration Verification
echo -e "${BLUE}⚙️  Step 7: Vercel Configuration Verification${NC}"
echo "--------------------------------------------"

# Check vercel.json
if [ -f "vercel.json" ]; then
    print_status "vercel.json configuration found"
    
    # Verify key settings
    if grep -q "nextjs" vercel.json; then
        print_status "Next.js framework detected in configuration"
    fi
    
    if grep -q "legacy-peer-deps" vercel.json; then
        print_status "Legacy peer deps configured"
    fi
else
    print_warning "vercel.json not found. Creating default configuration..."
    
    cat > "vercel.json" << EOF
{
  "version": 2,
  "framework": "nextjs",
  "installCommand": "npm install --legacy-peer-deps",
  "buildCommand": "npm run build",
  "outputDirectory": ".next",
  "devCommand": "npm run dev",
  "env": {
    "ENABLE_EXPERIMENTAL_COREPACK": "0",
    "npm_config_user_agent": "npm"
  },
  "build": {
    "env": {
      "NEXT_TELEMETRY_DISABLED": "1",
      "NODE_OPTIONS": "--max-old-space-size=4096"
    }
  }
}
EOF
    print_status "Default vercel.json created"
fi

# Check .vercelignore
if [ -f ".vercelignore" ]; then
    print_status ".vercelignore found"
else
    print_info "Creating .vercelignore..."
    
    cat > ".vercelignore" << EOF
node_modules
.next
.env.local
.env.development.local
.env.test.local
.env.production.local
.DS_Store
*.tgz
*.tar.gz
.cache
.parcel-cache
.nyc_output
.vercel
.turbo
dist
coverage
.git
*.md
!README.md
*.log
EOF
    print_status ".vercelignore created"
fi

echo ""

# 8. Security and Performance Checks
echo -e "${BLUE}🔒 Step 8: Security and Performance Checks${NC}"
echo "----------------------------------------"

# Check for sensitive files
SENSITIVE_FILES=(".env" ".env.local" ".env.production")
for file in "${SENSITIVE_FILES[@]}"; do
    if [ -f "$file" ]; then
        if grep -q "$file" .gitignore 2>/dev/null; then
            print_status "$file is properly ignored by git"
        else
            print_warning "$file should be added to .gitignore"
        fi
    fi
done

# Check Next.js configuration
if [ -f "next.config.js" ]; then
    print_status "Next.js configuration found"
    
    if grep -q "compress: true" next.config.js; then
        print_status "Compression enabled"
    fi
    
    if grep -q "reactStrictMode: true" next.config.js; then
        print_status "React strict mode enabled"
    fi
    
    if grep -q "poweredByHeader: false" next.config.js; then
        print_status "Powered by header disabled"
    fi
fi

echo ""

# 9. Database Schema Verification
echo -e "${BLUE}🗄️  Step 9: Database Schema Verification${NC}"
echo "-------------------------------------"

# Check for database schema files
if [ -f "lib/db-schema.ts" ]; then
    print_status "Database schema found: lib/db-schema.ts"
    
    # Check for required tables
    REQUIRED_TABLES=("organizations" "users" "documents" "documentSignatures")
    for table in "${REQUIRED_TABLES[@]}"; do
        if grep -q "$table" lib/db-schema.ts; then
            print_status "Table schema found: $table"
        else
            print_warning "Table schema missing: $table"
        fi
    done
else
    print_warning "Database schema not found at lib/db-schema.ts"
fi

echo ""

# 10. Final Deployment Summary
echo -e "${BLUE}🎯 Step 10: Deployment Summary${NC}"
echo "----------------------------"

echo ""
print_status "🎉 PULSE CRM DEPLOYMENT PREPARATION COMPLETE!"
echo ""

echo -e "${GREEN}✅ READY FOR VERCEL DEPLOYMENT${NC}"
echo ""

echo -e "${YELLOW}📋 NEXT STEPS:${NC}"
echo "1. Go to https://vercel.com/new"
echo "2. Import your GitHub repository"
echo "3. Configure environment variables using DEPLOYMENT_INSTRUCTIONS.md"
echo "4. Set Node.js version to 20.x in project settings"
echo "5. Deploy!"
echo ""

echo -e "${YELLOW}📁 GENERATED FILES:${NC}"
echo "- .env.production (production environment variables)"
echo "- DEPLOYMENT_INSTRUCTIONS.md (copy/paste instructions for Vercel)"
echo ""

echo -e "${YELLOW}🔑 GENERATED SECRETS:${NC}"
echo "- NEXTAUTH_SECRET: $NEXTAUTH_SECRET"
echo "  (32-character secure secret for authentication)"
echo ""

echo -e "${YELLOW}⚠️  MANUAL CONFIGURATION REQUIRED:${NC}"
echo "1. Update database URLs with your Neon PostgreSQL credentials"
echo "2. Update NEXTAUTH_URL with your actual Vercel app URL"
echo "3. Configure SMTP credentials for email functionality"
echo "4. Set up custom domain (optional)"
echo ""

echo -e "${GREEN}🚀 Your Pulse CRM is now ready for production deployment!${NC}"
echo ""

# Create deployment checklist
cat > "DEPLOYMENT_CHECKLIST.md" << EOF
# 📋 Pulse CRM Deployment Checklist

## Pre-Deployment ✅
- [x] Environment variables generated
- [x] Production build tested
- [x] Dependencies verified
- [x] Security checks completed
- [x] Git repository prepared

## Vercel Setup ⏳
- [ ] Import GitHub repository to Vercel
- [ ] Set Node.js version to 20.x
- [ ] Add environment variables from DEPLOYMENT_INSTRUCTIONS.md
- [ ] Configure custom domain (optional)

## Post-Deployment ⏳
- [ ] Test authentication flow
- [ ] Verify database connection
- [ ] Test email functionality
- [ ] Check document upload/download
- [ ] Verify e-signature workflow

## Database Setup ⏳
- [ ] Create Neon PostgreSQL database
- [ ] Update POSTGRES_URL environment variable
- [ ] Run initial database migration
- [ ] Test database connectivity

## Production Validation ⏳
- [ ] Site loads without errors
- [ ] User registration works
- [ ] Login/logout functionality
- [ ] Dashboard displays correctly
- [ ] All pages accessible
- [ ] Mobile responsiveness verified

Generated: $(date)
EOF

print_status "Deployment checklist created: DEPLOYMENT_CHECKLIST.md"

echo -e "${BLUE}🎯 Deployment preparation completed successfully!${NC}"

exit 0